[package]
name = "anno"
version = "0.1.2"
edition = "2021"

[[bin]]
name = "anno"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.18", features = ["derive", "cargo"] }
dirs = "5.0.1"
sha2 = "0.10.6"
